import { Bet } from "@/types";
import { users } from "./users";
import { getCategories } from "./categories";
import { betsTranslations } from "./betsTranslations";

type BetData = Omit<Bet, "title" | "shortDescription" | "fullDescription" | "outcome" | "category"> & {
  categoryId: string;
};

const betsData: BetData[] = [
  {
    id: "1",
    author: users[1],
    categoryId: "crypto",
    betAmount: 10000,
    coefficient: 3.2,
    potentialWinnings: 32000,
    status: "open",
    deadline: new Date("2026-02-15"),
    eventDate: new Date("2025-12-31"),
    location: "Global",
    verificationSource: "CoinMarketCap, CoinGecko",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    tags: ["Bitcoin", "BTC", "Halving", "ETF"],
    commentsCount: 1,
    betsCount: 134,
    likesCount: 24,
    likedByMe: true,
  },
  {
    id: "2",
    author: users[0],
    categoryId: "entertainment",
    betAmount: 3500,
    coefficient: 2.0,
    potentialWinnings: 7000,
    status: "open",
    deadline: new Date("2026-02-20"),
    eventDate: new Date("2026-02-15"),
    location: "USA",
    verificationSource: "Box Office Mojo",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    tags: ["Dune", "Movie", "Blockbuster"],
    commentsCount: 0,
    betsCount: 23,
    likesCount: 5,
    likedByMe: false,
  },
  {
    id: "3",
    author: users[2],
    categoryId: "stock-market",
    betAmount: 5000,
    coefficient: 2.5,
    potentialWinnings: 12500,
    status: "open",
    deadline: new Date("2025-12-31"),
    location: "USA",
    verificationSource: "Yahoo Finance, Bloomberg",
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    tags: ["S&P 500", "Stocks", "Index"],
    commentsCount: 3,
    betsCount: 67,
    likesCount: 18,
    likedByMe: false,
  },
  {
    id: "4",
    author: users[3],
    categoryId: "sports",
    betAmount: 2000,
    coefficient: 5.0,
    potentialWinnings: 10000,
    status: "open",
    deadline: new Date("2026-07-15"),
    location: "Russia",
    verificationSource: "FIFA official website",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    tags: ["Football", "World Cup", "Russia"],
    commentsCount: 5,
    betsCount: 89,
    likesCount: 32,
    likedByMe: true,
  },
  {
    id: "5",
    author: users[4],
    categoryId: "crypto",
    betAmount: 7500,
    coefficient: 2.8,
    potentialWinnings: 21000,
    status: "open",
    deadline: new Date("2025-12-31"),
    verificationSource: "CoinMarketCap",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    tags: ["Ethereum", "ETH", "DeFi"],
    commentsCount: 2,
    betsCount: 45,
    likesCount: 15,
    likedByMe: false,
  },
  {
    id: "6",
    author: users[5],
    categoryId: "technology",
    betAmount: 3000,
    coefficient: 3.5,
    potentialWinnings: 10500,
    status: "open",
    deadline: new Date("2025-12-31"),
    verificationSource: "Apple official website",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    tags: ["Apple", "AR", "Technology"],
    commentsCount: 4,
    betsCount: 56,
    likesCount: 21,
    likedByMe: false,
  },
  {
    id: "7",
    author: users[6],
    categoryId: "politics",
    betAmount: 1500,
    coefficient: 1.5,
    potentialWinnings: 2250,
    status: "completed",
    deadline: new Date("2024-12-31"),
    verificationSource: "Official election results",
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    tags: ["Politics", "USA", "Elections"],
    commentsCount: 12,
    betsCount: 234,
    likesCount: 89,
    likedByMe: true,
  },
  {
    id: "8",
    author: users[7],
    categoryId: "stock-market",
    betAmount: 4000,
    coefficient: 2.2,
    potentialWinnings: 8800,
    status: "open",
    deadline: new Date("2025-12-31"),
    verificationSource: "NASDAQ",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    tags: ["Tesla", "TSLA", "Stocks"],
    commentsCount: 1,
    betsCount: 34,
    likesCount: 11,
    likedByMe: false,
  },
  {
    id: "9",
    author: users[8],
    categoryId: "crypto",
    betAmount: 2500,
    coefficient: 4.0,
    potentialWinnings: 10000,
    status: "open",
    deadline: new Date("2025-12-31"),
    verificationSource: "CoinMarketCap",
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000),
    tags: ["Solana", "SOL", "Cryptocurrency"],
    commentsCount: 0,
    betsCount: 28,
    likesCount: 9,
    likedByMe: false,
  },
  {
    id: "10",
    author: users[9],
    categoryId: "sports",
    betAmount: 1800,
    coefficient: 2.8,
    potentialWinnings: 5040,
    status: "open",
    deadline: new Date("2026-02-28"),
    location: "France",
    verificationSource: "Olympics official website",
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    tags: ["Olympics", "Sports", "Russia"],
    commentsCount: 2,
    betsCount: 41,
    likesCount: 16,
    likedByMe: false,
  },
  {
    id: "11",
    author: users[10],
    categoryId: "entertainment",
    betAmount: 6000,
    coefficient: 2.5,
    potentialWinnings: 15000,
    status: "open",
    deadline: new Date("2026-12-31"),
    verificationSource: "Box Office Mojo",
    createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000),
    tags: ["Avatar", "Movie", "Blockbuster"],
    commentsCount: 3,
    betsCount: 78,
    likesCount: 45,
    likedByMe: true,
  },
  {
    id: "12",
    author: users[11],
    categoryId: "technology",
    betAmount: 4500,
    coefficient: 3.0,
    potentialWinnings: 13500,
    status: "open",
    deadline: new Date("2025-12-31"),
    verificationSource: "OpenAI official website",
    createdAt: new Date(Date.now() - 9 * 60 * 60 * 1000),
    tags: ["GPT-5", "AI", "OpenAI"],
    commentsCount: 6,
    betsCount: 92,
    likesCount: 56,
    likedByMe: false,
  },
  {
    id: "13",
    author: users[12],
    categoryId: "economy",
    betAmount: 2200,
    coefficient: 2.3,
    potentialWinnings: 5060,
    status: "open",
    deadline: new Date("2025-12-31"),
    location: "Russia",
    verificationSource: "Rosstat",
    createdAt: new Date(Date.now() - 11 * 60 * 60 * 1000),
    tags: ["Inflation", "Economy", "Russia"],
    commentsCount: 1,
    betsCount: 19,
    likesCount: 7,
    likedByMe: false,
  },
  {
    id: "14",
    author: users[13],
    categoryId: "crypto",
    betAmount: 3200,
    coefficient: 3.5,
    potentialWinnings: 11200,
    status: "open",
    deadline: new Date("2025-12-31"),
    verificationSource: "CoinMarketCap",
    createdAt: new Date(Date.now() - 13 * 60 * 60 * 1000),
    tags: ["BNB", "Binance", "Cryptocurrency"],
    commentsCount: 2,
    betsCount: 37,
    likesCount: 14,
    likedByMe: false,
  },
  {
    id: "15",
    author: users[14],
    categoryId: "stock-market",
    betAmount: 5500,
    coefficient: 2.1,
    potentialWinnings: 11550,
    status: "open",
    deadline: new Date("2025-12-31"),
    verificationSource: "NASDAQ",
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000),
    tags: ["Amazon", "AMZN", "Stocks"],
    commentsCount: 4,
    betsCount: 63,
    likesCount: 29,
    likedByMe: true,
  },
  {
    id: "16",
    author: users[15],
    categoryId: "sports",
    betAmount: 1200,
    coefficient: 4.5,
    potentialWinnings: 5400,
    status: "open",
    deadline: new Date("2025-05-31"),
    verificationSource: "IIHF official website",
    createdAt: new Date(Date.now() - 15 * 60 * 60 * 1000),
    tags: ["Hockey", "World Cup", "Russia"],
    commentsCount: 1,
    betsCount: 15,
    likesCount: 6,
    likedByMe: false,
  },
  {
    id: "17",
    author: users[1],
    categoryId: "crypto",
    betAmount: 2800,
    coefficient: 3.8,
    potentialWinnings: 10640,
    status: "open",
    deadline: new Date("2025-12-31"),
    verificationSource: "CoinMarketCap",
    createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000),
    tags: ["Cardano", "ADA", "Cryptocurrency"],
    commentsCount: 0,
    betsCount: 22,
    likesCount: 8,
    likedByMe: false,
  },
  {
    id: "18",
    author: users[2],
    categoryId: "stock-market",
    betAmount: 4800,
    coefficient: 2.4,
    potentialWinnings: 11520,
    status: "open",
    deadline: new Date("2025-12-31"),
    verificationSource: "NASDAQ",
    createdAt: new Date(Date.now() - 17 * 60 * 60 * 1000),
    tags: ["Microsoft", "MSFT", "Stocks"],
    commentsCount: 2,
    betsCount: 48,
    likesCount: 19,
    likedByMe: false,
  },
  {
    id: "19",
    author: users[3],
    categoryId: "sports",
    betAmount: 1600,
    coefficient: 3.2,
    potentialWinnings: 5120,
    status: "open",
    deadline: new Date("2025-08-31"),
    verificationSource: "FINA official website",
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
    tags: ["Swimming", "World Championships", "Russia"],
    commentsCount: 1,
    betsCount: 31,
    likesCount: 12,
    likedByMe: false,
  },
];

export const getBets = (locale: string = "en"): Bet[] => {
  const categories = getCategories(locale);
  const lang = locale === "ru" ? "ru" : "en";

  return betsData.map((bet) => {
    const translation = betsTranslations[bet.id]?.[lang];
    const category = categories.find((cat) => cat.id === bet.categoryId) || categories[0];

    return {
      ...bet,
      title: translation?.title || "",
      shortDescription: translation?.shortDescription || "",
      fullDescription: translation?.fullDescription || "",
      outcome: translation?.outcome || "",
      category,
    } as Bet;
  });
};

// For backward compatibility, export default English bets
export const bets = getBets("en");
