import { User } from "@/types";

export const users: User[] = [
  {
    id: "1",
    username: "Вы",
    rating: 4.2,
    winRate: 68,
    verified: true,
    joinedDate: new Date("2025-07-30"),
    location: "Москва",
    totalBets: 24,
    interests: ["stock-market", "technology", "crypto"],
    earnings: 0,
    rank: 1,
  },
  {
    id: "2",
    username: "CryptoWhale",
    rating: 4.3,
    winRate: 69,
    verified: true,
    joinedDate: new Date("2025-01-15"),
    location: "Санкт-Петербург",
    totalBets: 45,
    interests: ["crypto"],
    earnings: 0,
    rank: 2,
  },
  {
    id: "3",
    username: "TraderAlex",
    rating: 4.8,
    winRate: 82,
    verified: true,
    joinedDate: new Date("2024-12-10"),
    location: "Новосибирск",
    totalBets: 67,
    interests: ["stock-market", "economy"],
    earnings: 0,
    rank: 3,
  },
  {
    id: "4",
    username: "СпортГуру",
    rating: 4.6,
    winRate: 74,
    verified: true,
    joinedDate: new Date("2025-01-05"),
    location: "Казань",
    totalBets: 52,
    interests: ["sports"],
    earnings: 0,
    rank: 4,
  },
  {
    id: "5",
    username: "AuctionMaster",
    rating: 4.4,
    winRate: 71,
    verified: true,
    joinedDate: new Date("2024-11-20"),
    location: "Екатеринбург",
    totalBets: 38,
    interests: ["entertainment", "technology"],
    earnings: 0,
    rank: 5,
  },
  {
    id: "6",
    username: "TechProphet",
    rating: 4.5,
    winRate: 76,
    verified: true,
    joinedDate: new Date("2024-10-15"),
    location: "Краснодар",
    totalBets: 41,
    interests: ["technology"],
    earnings: 0,
    rank: 6,
  },
  {
    id: "7",
    username: "PolAnalyst",
    rating: 4.1,
    winRate: 65,
    verified: true,
    joinedDate: new Date("2025-01-10"),
    location: "Воронеж",
    totalBets: 29,
    interests: ["politics"],
    earnings: 0,
    rank: 7,
  },
  {
    id: "8",
    username: "MarketWizard",
    rating: 4.7,
    winRate: 79,
    verified: true,
    joinedDate: new Date("2024-09-05"),
    location: "Нижний Новгород",
    totalBets: 58,
    interests: ["stock-market", "economy"],
    earnings: 0,
    rank: 8,
  },
  {
    id: "9",
    username: "CryptoExpert",
    rating: 4.3,
    winRate: 70,
    verified: true,
    joinedDate: new Date("2025-01-20"),
    location: "Сочи",
    totalBets: 33,
    interests: ["crypto"],
    earnings: 0,
    rank: 9,
  },
  {
    id: "10",
    username: "SportFan",
    rating: 4.0,
    winRate: 63,
    verified: false,
    joinedDate: new Date("2025-01-25"),
    location: "Ростов-на-Дону",
    totalBets: 18,
    interests: ["sports"],
    earnings: 0,
    rank: 10,
  },
  {
    id: "11",
    username: "EntertainmentGuru",
    rating: 4.2,
    winRate: 67,
    verified: true,
    joinedDate: new Date("2024-12-01"),
    location: "Самара",
    totalBets: 36,
    interests: ["entertainment"],
    earnings: 0,
    rank: 11,
  },
  {
    id: "12",
    username: "TechGuru",
    rating: 4.4,
    winRate: 72,
    verified: true,
    joinedDate: new Date("2024-11-10"),
    location: "Уфа",
    totalBets: 44,
    interests: ["technology"],
    earnings: 0,
    rank: 12,
  },
  {
    id: "13",
    username: "EconomyPro",
    rating: 4.1,
    winRate: 66,
    verified: false,
    joinedDate: new Date("2025-01-15"),
    location: "Красноярск",
    totalBets: 27,
    interests: ["economy"],
    earnings: 0,
    rank: 13,
  },
  {
    id: "14",
    username: "CryptoTrader",
    rating: 4.5,
    winRate: 75,
    verified: true,
    joinedDate: new Date("2024-10-20"),
    location: "Пермь",
    totalBets: 49,
    interests: ["crypto"],
    earnings: 0,
    rank: 14,
  },
  {
    id: "15",
    username: "StockMaster",
    rating: 4.6,
    winRate: 77,
    verified: true,
    joinedDate: new Date("2024-09-15"),
    location: "Волгоград",
    totalBets: 55,
    interests: ["stock-market"],
    earnings: 0,
    rank: 15,
  },
  {
    id: "16",
    username: "NewPlayer",
    rating: 3.8,
    winRate: 58,
    verified: false,
    joinedDate: new Date("2025-01-26"),
    location: "Челябинск",
    totalBets: 12,
    interests: ["sports"],
    earnings: 0,
    rank: 16,
  },
];
